# Generated by Django 3.1.5 on 2021-01-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_book_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.FloatField(default=5, verbose_name='rating'),
        ),
    ]
