# Generated by Django 3.1.5 on 2021-01-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_usersrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_users',
            field=models.PositiveIntegerField(default=0, verbose_name='counted_users'),
        ),
        migrations.AddField(
            model_name='book',
            name='users_counted_stars',
            field=models.PositiveIntegerField(default=0, verbose_name='counted_stars'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
