# Generated by Django 3.1.5 on 2021-01-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_auto_20210118_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
