# Generated by Django 3.1.5 on 2021-01-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20210118_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users_like',
        ),
        migrations.DeleteModel(
            name='LikeBookUser',
        ),
    ]
