# Generated by Django 3.1.5 on 2021-01-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_auto_20210121_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(null=True, verbose_name=models.CharField(max_length=250)),
        ),
    ]
