# Generated by Django 3.1.5 on 2021-01-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
