# Generated by Django 3.1.5 on 2021-01-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_auto_20210124_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коммментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
