# Generated by Django 3.1.5 on 2021-01-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_testtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtable',
            name='some',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
