# Generated by Django 3.1.5 on 2021-01-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_testtable_some'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
