# Generated by Django 3.1.5 on 2021-01-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_delete_testtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date-time'),
        ),
    ]
